language: php
php:
- '5.6'
- '7.1'
install:
- composer install
script:
- ./vendor/bin/phing test
after_script:
- if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then ./vendor/bin/coveralls -vvv; fi;
notifications:
  email:
    recipients:
    - nicolas@2dotstwice.be
    - bert@2dotstwice
