debug: false
bootstrap: []
consumerExecutionDelay: 4
amqp:
  host: example.com
  port: 5672
  vhost: example
  user: foo
  password: bar
  consumer_tag: udb3
  consumers:
    udb3-core:
      exchange: udb3.e.udb3
      queue: udb3.q.udb3-cdbxml
  publishers:
    udb2:
      exchange: udb2.e.prod
