debug: false
bootstrap: []
consumerExecutionDelay: 4
url: http://culudb-cdbxml.dev:8080
amqp:
  host: example.com
  port: 5672
  vhost: udb3-udb2acc
  user: username
  password: pwd
  consumer_tag: consumer-tag
  consumers:
    udb3-core:
      exchange: udb3.e.udb3
      queue: udb3.q.udb3-cdbxml
  publishers:
    udb2:
      exchange: udb2.e.prod
cache:
  redis:
    host: 127.0.0.1
    database: 1
database:
  driver: pdo_mysql
  dbname: culudb-cdbxml
  user: usernname
  password: pwd
  host: 127.0.0.1
offer_url_regex: https?://culudb-cdbxml\.dev/(?<offertype>[event|place]+)/(?<offerid>[a-zA-Z0-9\-]+)
uitpas_service:
  labels_url: http://udb-uitpas.dev/labels
