debug: false
bootstrap: []
consumerExecutionDelay: 4
amqp:
  host: orange-gnu.rmq.cloudamqp.com
  port: 5672
  vhost: udb3-udb2acc
  user: username
  password: pwd
  consumer_tag: consumer-tag
  consumers:
    udb3-core:
      exchange: exchange-name
      queue: queue-name
cache:
  redis:
    host: 127.0.0.1
    database: 1
